name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Create Tag
        run: |
          git tag v${{ steps.semver.outputs.next }}
          git push origin v${{ steps.semver.outputs.next }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          tag: v${{ steps.semver.outputs.next }} # Используем тег
          body: Changelog Contents
          token: ${{ github.token }}
